[package]
name = "witness-encryption-functional-commitment"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
sha3 = "0.10.6"
nalgebra = "0.31.4"
bitvec = "1.0.1"
bls12_381 = "0.8.0"
ff = "0.13.0"
group = "0.13.0"
pairing = "0.23.0"

